### ISSUE TITLE
`get_azure_token()` raises error "nul in string"

### ISSUE THREAD

**Issue by nteetor** [Azure/AzureAuth#16]
Thank you for the package. I am using the `get_azure_token()` function with auth type "authorization_code". It took a little bit of praying and guess work to get this point. The errors about scope and client_secret have finally gone away. However, I am now running into this error about converting the decoded token from raw to character. I realize the error is in `rawToChar()`, a {base} function. I'm wondering if you can suggest a strategy for working around this error. Is it safe to drop these nul characters and then convert to character?

I can't provide my config file to recreate the problem, but at a high level here is my call to `get_azure_token()`, 

```R
azure <- config::get("azure")
    
with(azure, {
  AzureAuth::get_azure_token(
    RESOURCE, TENANT, APP,
    password = SECRET,
    auth_type = "authorization_code",
    authorize_args = list(redirect_uri = REDIRECT, scope = SCOPE),
    use_cache = FALSE,
    auth_code = code,   # function argument, code retrieved per the shiny vignette
    version = 2
  )
})
```

Do you happen to see anything grossly wrong with my function call?

Any and all help is appreciated!

Tangentially, having some version 2 examples in a vignette would be extremely helpful.

**Comment by Hong-Revo** [comment]
1. See the help for `get_azure_token` for how to specify scopes for a V2 token. You don't set the scope via `authorize_args`.
2. Is your registered app in AAD a native or webapp?
3. I assume this is for Shiny?

**Comment by nteetor** [comment]
1. I'll review the docs again, I did before. These arguments finally got a result for me, other than the parsing error.
2. This is a web app.
3. And yep, we're using shiny.

**Comment by nteetor** [comment]
Hello again @Hong-Revo, I dropped scope from `authorize_args`, but unfortunately I am still running into the embedded nul error.

I added openid to `resource`, which is now `c("https://management.azure.com", "openid")`. Perhaps I misunderstand which resources need to be passed?

**Comment by nteetor** [comment]
If I remove `auth_type = "authorization_code"` I no longer have the embedded nul error, but then I get the error,

```
Warning: 
  Error in process_aad_response: Bad Request (HTTP 400). 
  Failed to obtain Azure Active Directory token. 
  Message:
    AADSTS70011: The provided request must include a 'scope' input parameter. 
    The provided value for the input parameter 'scope' is not valid. 
    The scope openid is not valid.
```

**Comment by Hong-Revo** [comment]
I suspect what's happening is that your calls to `get_azure_token` and `build_authorization_uri` are out of sync. They should be like this:

```r
# in UI
...
uri <- build_authorization_uri(c("openid", "offline_access"), tenant, app, pwd, version=2)
...

# in Server
...
token <- get_azure_token(c("openid", "offline_access"), tenant, app, pwd, version=2,
                         auth_type="authorization_code")
...
```

All the args must match, except for `auth_type` (which is superfluous for `build_authorization_uri`). If this doesn't solve the problem, show your calls to these funcs.

**Comment by nteetor** [comment]
I was able to make a little more headway, thank you. 

I am concerned about the fourth argument to `build_authorization()`. The argument is `username`, but based on the example above I pass the password/secret. This secret is then shown as the hint on the authorization page. In contrast, the fourth argument for `get_azure_token()` is `password`.  Should I pass different argument to `build_authorization_uri()`'s `username`? Can I drop the argument altogether?

**Comment by nteetor** [comment]
In case you would like to see them, here are my uses of `build_authorization_uri()` and `get_azure_token()`,

```R
azure_auth_redirect <- function(code) {
  if (is.null(code)) {
    azure <- config::get("azure")
    
    uri <- with(azure, {
      AzureAuth::build_authorization_uri(
        resource = RESOURCE, 
        tenant = TENANT, 
        app = APP, 
        # username = SECRET,
        redirect_uri = REDIRECT,
        version = 2
      )
    })
    
    tags$script(HTML(glue::glue("window.location.replace(\"{ uri }\");")))
  }
}

azure_auth_retrieve <- function(code) {
  if (!is.null(code)) {
    azure <- config::get("azure")
    
    httr::with_verbose(with(azure, {
      AzureAuth::get_azure_token(
        resource = RESOURCE, 
        tenant = TENANT, 
        app = APP,
        password = SECRET,
        auth_type = "authorization_code",
        authorize_args = list(redirect_uri = REDIRECT),
        auth_code = code,
        version = 2
      )
    }))
  }
}
```

**Comment by nteetor** [comment]
I am still running into the embedded null error despite getting a `200` response from the server. 

Is there any chance there's a decoding error due to my operating system? We're developing on Mac.

**Comment by Hong-Revo** [comment]
Oops, forgot that you don't send passwords to the authorization endpoint. Drop that from `build_authorization_uri`.

The error you're getting is because the token endpoint is, for some reason, sending you a V1 response instead of V2. To simplify things, drop Shiny. Run this, and see what it gets you:

```r
resource <- "openid"
auth_uri <- build_authorization_uri(resource, tenant, app, redirect_uri=redirect, version=2)
code <- AzureAuth:::listen_for_authcode(auth_uri, redirect)
tok <- get_azure_token(resource, tenant, app, version=2, auth_code=code,
                       authorize_args=list(redirect_uri=redirect),
                       use_cache=FALSE)
```

**Comment by nteetor** [comment]
Okay, I will get those results. I'll feel foolish if this is a misconfiguration issue I introduced elsewhere.

**Comment by nteetor** [comment]
Here's what I got at first,

##### code (1)

```R
azure <- config::get("azure")

with(azure, {
  auth_uri <- AzureAuth::build_authorization_uri(
    "openid", TENANT, APP,
    redirect_uri=REDIRECT, version=2
  )
  code <- AzureAuth:::listen_for_authcode(auth_uri, REDIRECT)
  tok <- AzureAuth::get_azure_token(
    "openid", TENANT, APP,
    version=2, auth_code=code,
    authorize_args=list(redirect_uri=REDIRECT),
    use_cache=FALSE
  )
})
```

##### result (1)

```
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in process_aad_response(res) : 
  Unauthorized (HTTP 401). Failed to obtain Azure Active Directory token. Message:
AADSTS70002: The provided request must include a 'client_secret' input parameter.
```

I then included `password` in the `get_azure_token()` call,

##### code (2)

```R
azure <- config::get("azure")

with(azure, {
  auth_uri <- AzureAuth::build_authorization_uri(
    "openid", TENANT, APP,
    redirect_uri=REDIRECT, version=2
  )
  code <- AzureAuth:::listen_for_authcode(auth_uri, REDIRECT)
  tok <- AzureAuth::get_azure_token(
    "openid", TENANT, APP,
    password = SECRET,  # <- added this line
    version=2, auth_code=code,
    authorize_args=list(redirect_uri=REDIRECT),
    use_cache=FALSE
  )
})
```

##### result (2)

```
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in process_aad_response(res) : 
  Bad Request (HTTP 400). Failed to obtain Azure Active Directory token. Message:
AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope openid is not valid.
```

##### http request/response (2)

<details>
  <summary>httr verbose output</summary>
 
```
-> POST /common/oauth2/v2.0/token HTTP/1.1
-> Host: login.microsoftonline.com
-> User-Agent: libcurl/7.54.0 r-curl/4.1 httr/1.4.0
-> Accept-Encoding: deflate, gzip
-> Cookie: fpc=AgE9S-3y0IJNjOJmwYr0KU2sfWnoAgAAAFTBNtUOAAAA; stsservicecookie=ests; x-ms-gateway-slice=prod
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/x-www-form-urlencoded
-> Content-Length: 142
-> 
>> client_id=<REDACTED>&grant_type=client_credentials&client_secret=<REDACTED>&scope=openid


<- HTTP/1.1 400 Bad Request
<- Cache-Control: no-cache, no-store
<- Pragma: no-cache
<- Content-Type: application/json; charset=utf-8
<- Expires: -1
<- Strict-Transport-Security: max-age=31536000; includeSubDomains
<- X-Content-Type-Options: nosniff
<- x-ms-request-id: ac87ef8e-9aae-4204-b4aa-820b4bff6a00
<- x-ms-ests-server: 2.1.9524.8 - EST ProdSlices
<- P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
<- Set-Cookie: fpc=AgE9S-3y0IJNjOJmwYr0KU2sfWnoAgAAAFTBNtUOAAAA; expires=Wed, 13-Nov-2019 19:25:17 GMT; path=/; secure; HttpOnly; SameSite=None
<- Set-Cookie: x-ms-gateway-slice=prod; path=/; secure; HttpOnly
<- Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
<- Date: Mon, 14 Oct 2019 19:25:16 GMT
<- Content-Length: 521
<- 
```

</details>

**Comment by Hong-Revo** [comment]
OK, I can repro the problem with a webapp, but not a native app. Not sure what's going on here.

**Comment by Hong-Revo** [comment]
It looks like AAD 2.0 doesn't allow webapps to retrieve only ID tokens, you have to provide an actual resource. The following works for me:

```r
resource <- c("https://graph.microsoft.com/.default", "openid", "offline_access")

auth_uri <- build_authorization_uri(resource, tenant, app, redirect_uri=redirect, version=2)
code <- AzureAuth:::listen_for_authcode(auth_uri, redirect)
tok <- get_azure_token(resource, tenant, app, version=2, auth_code=code,
                       authorize_args=list(redirect_uri=redirect),
                       use_cache=FALSE)
```

**Comment by nteetor** [comment]
That appears to have worked! Thank you so much for the fast responses and all the help.

**Comment by Hong-Revo** [comment]
It's a bit of a hack though. I'll build in real support for the Open ID flow, rather than tacking it on to auth_code.
