### ISSUE TITLE
Allow more authorization arguments

### ISSUE THREAD

**Issue by nteetor** [Azure/AzureAuth#22]
Right now in `build_authorization_uri()` the use of `utils::modifyList()` means certain valid authorization arguments (such as `prompt`) may be passed without raising a warning, but the argument is completely ignored. This is because the `default_opts` variable only includes a subset of the possible uri arguments found here, https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#request-an-authorization-code. 

I would prefer the function trust the developer and pass on all values. Otherwise, at the very least I hope the function can support all possible arguments. In my case I was hoping to change the `prompt` value. I was able to successfully achieve this by installing a custom version of AzureAuth where I added `prompt = . . .` to the `default_opts` variable in `build_authorization_uri()`.

**Comment by Hong-Revo** [comment]
I don't see what the problem is.

```
build_authorization_uri("https://graph.microsoft.com", "mytenant",
    app="11111111-2222-3333-4444-555555555555",
    redirect_uri="http://localhost:8000",
    prompt="login")

[1] "https://login.microsoftonline.com/mytenant.onmicrosoft.com/oauth2/authorize?
client_id=11111111-2222-3333-4444-555555555555&
response_type=code&
redirect_uri=http%3A%2F%2Flocalhost%3A8000&
state=twumepbhwhffstlpgjvg&
resource=https%3A%2F%2Fgraph.microsoft.com&
prompt=login"
^^^^^^^^^^^^
```

**Comment by Hong-Revo** [comment]
PS. please add a reprex if you're reporting an issue, it makes it a lot easier to see what's going on.

https://stackoverflow.com/help/minimal-reproducible-example
https://cran.r-project.org/web/packages/reprex/vignettes/reprex-dos-and-donts.html
