### ISSUE TITLE
Connect databricks to SQL database using service principal

### ISSUE THREAD

**Issue by n8shadow** [Azure/AzureAuth#23]
I would like to connect Databricks to SQL DB using service principal via ADD autentication. 

[Here](https://thedataguy.blog/connect-azure-databricks-to-sql-database-azure-sql-data-warehouse-using-a-service-principal/) it is described how to do so using scala. Is there a similar solution in the AzureR world? If not, do you know any workaround to achive the same result?

**Comment by Hong-Revo** [comment]
I think you only need authentication to work? If so, you can get the token as follows:

```
tok <- AzureAuth::get_azure_token("https://database.windows.net", "tenantid", "svc_principal_id",
    password="password")

access_token <- tok$credentials$access_token
```

I haven't used Databricks much, but you should be able to find code that uses Sparklyr to connect to databases. `access_token` is the equivalent of `accessToken` in the linked example.
