### ISSUE TITLE
Setup Instructions for Azure App - same as AzureSMR??

### ISSUE THREAD

**Issue by j450h1** [Azure/AzureAuth#25]
I setup an App to use with AzureSMR a few years back. Now I'm trying to authenticate with that same app and credentials , but having some issues. 

```
library(AzureAuth)
token <- get_azure_token(
  resource = RESOURCE_GROUP,
  tenant = Sys.getenv("TENANT_ID"),
  app = Sys.getenv("APPLICATION_ID"),
  password = Sys.getenv("AUTHENTICATION_KEY"), 
  auth_type="client_credentials"
```  
**Error in process_aad_response(res) :**
  _Bad Request (HTTP 400). Failed to obtain Azure Active Directory token. Message:
AADSTS500011: The resource principal named {REDACTED} was not found in the tenant named {REDACTED}. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: a9c03f3a-8291-453a-841b-5ac272f21d01
Correlation ID: 6c9f6d9c-2961-4a58-a3bf-6a9ac3f48ab5
Timestamp: 2020-03-04 02:13:42Z._

Can you link to the official setup instructions that work with this package or confirm that these instructions are still valid:
https://github.com/Microsoft/AzureSMR/blob/master/vignettes/Authentication.Rmd
?

**Comment by Hong-Revo** [comment]
Hi,

First, AzureAuth/RMR is independent of AzureSMR. The packages share some features and AzureSMR was the inspiration for this effort, but otherwise they are unrelated.

Also, if you're working with Resource Manager, you shouldn't need to make a service principal for AzureRMR. Just run `create_azure_login()` and it will handle the authentication details automatically.

AzureRMR includes a vignette for registering an app/service principal manually, if this is required. You can find it on CRAN [here.](https://cran.r-project.org/web/packages/AzureRMR/vignettes/sp.html) Creating/registering an app in general is a broad topic, and you should [consult the Azure docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) for more information.

**Comment by Hong-Revo** [comment]
Can you give more details on your use case? Chances are if you're not using the app to talk to Resource Manager, you'll need to add the correct permissions so the app can access your resource.

**Comment by j450h1** [comment]
Ultimately, all I want to do is download objects from blob storage (using AzureStor). It would be nice to have a way that it works non-interactively, but for this use case its fine if I periodically login. 

I will try the ```create_azure_login()``` function you alluded to.

**Comment by Hong-Revo** [comment]
Downloading a file from storage is different to working with Resource Manager. `create_azure_login` is strictly for the latter.

You can create a new app/service principal, and give it the appropriate access rights to your storage account. You probably want "storage blob data contributor".

**Comment by j450h1** [comment]
Thanks for clarifying. I will proceed with creating a new app/service principal with those access rights.

**Comment by j450h1** [comment]
Do you know why I don't see the **"storage blob data contributor"** here (instead only user_impersonation was available to select). Also why are Application Permissions greyed out?:

![image](https://user-images.githubusercontent.com/7351530/75934043-53777400-5e30-11ea-82ff-8cedfb4ced2f.png)

I provided this App with full Owner permissions needed to the storage account itself as per below (App name is AzureStor:

![image](https://user-images.githubusercontent.com/7351530/75941622-08b42700-5e45-11ea-9e3e-8d55bc508038.png)

I'm not able to list files as per below (or download files):
```
library(AzureStor)

token <- AzureRMR::get_azure_token("https://storage.azure.com",
  tenant = Sys.getenv("TENANT_ID"), 
  app = Sys.getenv("APPLICATION_ID"), 
  password = Sys.getenv("AUTHENTICATION_KEY")
)

bl_endp_tok <- storage_endpoint(Sys.getenv('STORAGE_ENDPOINT'), token = token)

# Works
#list_storage_containers(bl_endp_tok)

cont <- storage_container(bl_endp_tok, Sys.getenv('CONTAINER_NAME'))

# Permission Error as per below
list_storage_files(cont)
```

**Comment by Hong-Revo** [comment]
"Storage blob data contributor" is a role you assign to your app, under "Access control" for the storage account.

![image](https://user-images.githubusercontent.com/11328890/75946712-da960d80-5e6b-11ea-855a-552c3046caea.png)

**Comment by j450h1** [comment]
Thanks alot @Hong-Revo! That was the missing piece. It works fine now that I have updated the IAM (I thought **Owner** was sufficient, which it isn't). I can list the files and also presume I will be able to download the file.
