### ISSUE TITLE
Possibility of connection external app

### ISSUE THREAD

**Issue by tomasj-ds** [Azure/AzureAuth#27]
Hi, 

i deployed app with help of AWS ECS, but users, who can visit my shiny app, have accounts in microsoft azure. I want use this package for single sign on option, it is possible for external apps, without registration in apps service, or in active directory in microsoft azure ?

**Comment by Hong-Revo** [comment]
I'm not sure what you mean. Do you want your users to signon to your app hosted in AWS, when they have MS accounts?

**Comment by tomasj-ds** [comment]
Yes,exactly

**Comment by Hong-Revo** [comment]
In that case, AzureAuth is the _opposite_ of what you need. You'd use this package if your app was in Azure, and you wanted people to signon with MS or non-MS accounts. I don't how how AWS handles auth in general, but you can ask on the RStudio community forums: https://community.rstudio.com
