### ISSUE TITLE
Support MSIs

### ISSUE THREAD

**Issue by Hong-Revo** [Azure/AzureAuth#3]
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-arm

```
curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/' -H Metadata:true
```

**Comment by Sharathmk99** [comment]
Does AzureAuth R package support Managed Identity Authentication?

**Comment by Hong-Revo** [comment]
Not yet, hence this issue. You can get the raw token with httr:

```
httr::GET("http://169.254.169.254/metadata/identity/oauth2/token",
          query=list(`api-version`="2018-02-01", resource="https://management.azure.com/"),
          httr::add_headers(Metadata="true"))
```

**Comment by Sharathmk99** [comment]
Once i get the RAW token i can directly access resource right, in my case i wanted to access Kayvault.

**Comment by Hong-Revo** [comment]
I've just made some changes to AzureKeyVault to enable using a string as a token. Give it a go and tell me if something breaks.

https://github.com/Azure/AzureKeyVault

**Comment by Sharathmk99** [comment]
From below code, i can get access token. But i'm not able to use get_managed_token("https://vault.azure.net/"). I get error like,
Error in utils::modifyList(self$credentials, creds) :
  is.list(val) is not TRUE

httr::GET("http://169.254.169.254/metadata/identity/oauth2/token",
          query=list(`api-version`="2018-02-01", resource="https://management.azure.com/"),
          httr::add_headers(Metadata="true"))

**Comment by Hong-Revo** [comment]
`get_managed_token("https://vault.azure.net/")` works for me, in a Linux DSVM. Try reinstalling AzureAuth from CRAN (not MRAN, if you're using Microsoft R).
