### ISSUE TITLE
Questions about redirect URL

### ISSUE THREAD

**Issue by tyluRp** [Azure/AzureAuth#41]
I have everything working thanks to your shiny app vignette. However, I've noticed that when I am redirected to the app, the URL gets quite messy and stays that way. I've also noticed that refreshing the page after redirect causes a crash. So I have a couple questions questions:

1. Is the URL with the token expected?
2. Is it possible to return the clean/original URL when redirected?
3. Is the crash I describe expected?

Regarding the crash, I've looked at the logs and I see:

```
Warning: Error in process_aad_response: Bad Request (HTTP 400). Failed to obtain Azure Active Directory token. Message:
AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.
Trace ID: REDACTED
Correlation ID: REDACTED
Timestamp: 2021-04-16 15:31:52Z.
  56: <Anonymous>
Error in process_aad_response(res) :
  Bad Request (HTTP 400). Failed to obtain Azure Active Directory token. Message:
AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.
Trace ID: REDACTED
Correlation ID: REDACTED
Timestamp: 2021-04-16 15:31:52Z.
```

**Comment by tyluRp** [comment]
Oh and one more thing! I have also noticed that once redirected, if I attempt to refresh the page the app will crash, is this also expected?

**Comment by hongooi73** [comment]
Do you mean the URL starting with `localhost:1410/?code=...`? Yes, that's expected. The URL is how the OAuth mechanism communicates the authorization code back to your machine; the code is then exchanged for the actual token. It's a one-time code, which is why you get the error message you see.

If you are running your app on a _server_ and not your local machine, you would need to set the redirect to the URL of the server. In that case, your users shouldn't see any messy redirects.

**Comment by hongooi73** [comment]
https://docs.microsoft.com/en-au/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by tyluRp** [comment]
> If you are running your app on a server and not your local machine, you would need to set the redirect to the URL of the server. In that case, your users shouldn't see any messy redirects.

The URL I am using is something like `shiny.example.com/my-app`. This is what I need right? If so, I will dig into that link you've provided as I am still getting the messy redirects.

**Comment by hongooi73** [comment]
Oh right, in that case let me know what you find. I'll admit I haven't actually tested this with Shiny much -- as far as I know it works but there may be hidden issues.

**Comment by tyluRp** [comment]
If I have a shiny app redirect to the base URL, `https://shiny.example.com`, it no longer complains and the URL remains 'messy'. So there is something about refreshing the page when its redirecting to the app itself, e.g. `https://shiny.example.com/my-app`. I'll let you know if I even resolve this.

**Comment by tyluRp** [comment]
So it seems that I can add the following javascript to get the clean URL:

```javascript
const nextURL = 'https://shiny.example.com/my-app';
const nextTitle = 'My new page title';
const nextState = { additionalInformation: 'Updated the URL with JS' };

// This will create a new entry in the browser's history, without reloading
window.history.pushState(nextState, nextTitle, nextURL);
```

When this is ran in the console, the URL is cleaned and a refresh no longer complaints about the token.

**Comment by hongooi73** [comment]
That's great! Would you consider making a PR to update the [shiny vignette](https://github.com/Azure/AzureAuth/blob/master/vignettes/shiny.Rmd)? I'm not a web dev so I'll accept any help I can get.

**Comment by tyluRp** [comment]
I would be happy to contribute! But fair warning that I am also not a web dev, so I am unsure if this is the cleanest solution available. I draft something up tonight and submit a PR.
