### ISSUE TITLE
Question: Obtain Token for user when deployed as Azure WebApp, to access SQL server

### ISSUE THREAD

**Issue by olesendan** [Azure/AzureAuth#45]
I'm posting here,because I use AzureAuth in my workflow.

I'm trying to deploy a shiny WebApp on Azure, which has a SQL server as backend. The server is secured with AAD. I ca't figure out how to get an access token for this senario.

I've posted the question on Stackoverflow, but hoping a user of AzureAuth, give provide a bit of guidience.

link to stackoverflow, where I've put must of my code.
https://stackoverflow.com/questions/67570465/shiny-azure-webapp-authenticate-as-user-to-azure-sql-server

**Comment by hongooi73** [comment]
AAD authentication with an OAuth token requires you to pass a pointer to the (UTF-16 encoded) token string: https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver15#authenticating-with-an-access-token

As far as I know, there is no easy way right now to incorporate this into the regular R packages for database connections (RODBC, odbc). There is an [open feature request](https://github.com/r-dbi/odbc/issues/299) for this at the odbc repo.
