### ISSUE TITLE
Adding Microsoft Graph Scopes to get_azure_token call

### ISSUE THREAD

**Issue by DataHippo93** [Azure/AzureAuth#5]
I am unable to add scopes that are not from openid for graph.microsoft.com

Specifically these: User.ReadBasic.All; User.Read.All; User.ReadWrite.All; Directory.Read.All; Directory.ReadWrite.All; Directory.AccessAsUser.All

I tried grabbing the scope GUID from the application manifest but the package appends /.default to them and makes them invalid.

Without the capability to add resource specific scopes I cannot call https://graph.microsoft.com/v1.0/groups with proper permissions in my access token.

Very useful package but this issue needs to be fixed.

**Comment by Hong-Revo** [comment]
Can you show the code that you're running to get the token? As well as the specific Graph endpoint you're trying to access?

**Comment by DataHippo93** [comment]
`azureResponse <- get_azure_token(c("https://graph.microsoft.com/.default", "offline_access", "openid", "email", "profile", "594c1fb6-4f81-4475-ae41-0c394909246c"),
                                 "TenantID", "AppID",password="Secret_Key", version=2)
`

I also tried this
which gives me this error:
`
Error in process_aad_response(res) : 
  Bad Request (HTTP 400). Failed to obtain Azure Active Directory token. Message:
AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/.default offline_access openid email profile 594c1fb6-4f81-4475-ae41-0c394909246c/.default is not valid.
Trace ID: 0e2ada87-0a05-4747-92f1-eea5bb3a0b00
Correlation ID: 792316fa-1067-48df-992b-862a94a33f5b
Timestamp: 2019-06-12 02:14:00Z.
In addition: Warning message:
No path supplied for scope 594c1fb6-4f81-4475-ae41-0c394909246c; setting to /.default 

`


`
azureResponse <- get_azure_token(c("https://graph.microsoft.com/.default", "offline_access", "openid", "email", "profile", "User.ReadBasic.All"),
                                 "TenantID", "AppID",password="Secret Key", version=2)
`

I get Error 

Error: Invalid scope (must be a URI or GUID): User.ReadBasic.All

If I run without the scope

**Comment by Hong-Revo** [comment]
To get a specific scope, add it to the endpoint URI _as a single string_:

```r
tok <- get_azure_token(
    c("https://graph.microsoft.com/User.Read.All",
      "https://graph.microsoft.com/User.ReadWrite.All",
      "https://graph.microsoft.com/Directory.ReadWrite.All",
      "offline_access"),
    tenant="tenant",
    app="app_id",
    version=2)
```

I'll add this to the documentation.

Note that you can only add user-level scopes like this with the authorization_code or device_code flows; the client_credentials flow won't work because there are no user credentials involved.

**Comment by DataHippo93** [comment]
Ok this makes sense but when I try to use your code with my app I get the following error: 

`Press Esc/Ctrl + C to abort
Authentication complete.
Error in process_aad_response(res) : 
  Unauthorized (HTTP 401). Failed to obtain Azure Active Directory token. Message:
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 7f99fbd8-4b88-4760-ad9a-c1520b812900
Correlation ID: 04090e14-a8ac-452b-88af-ac52ba4f4dd7
Timestamp: 2019-06-12 10:51:19Z.`

**Comment by Hong-Revo** [comment]
Please provide the actual code you ran that resulted in the error.

**Comment by DataHippo93** [comment]
`tok <- get_azure_token(
  c(
    "https://graph.microsoft.com/User.Read.All",
    "https://graph.microsoft.com/User.ReadWrite.All",
    "https://graph.microsoft.com/Directory.ReadWrite.All",
    "offline_access"),
  tenant="tenantID", 
  app="AppID",
   auth_type="authorization_code",
  version=2)`

**Comment by DataHippo93** [comment]
![image](https://user-images.githubusercontent.com/20848101/59348055-c55ed900-8d48-11e9-8b89-8df14d4d4674.png)

![image](https://user-images.githubusercontent.com/20848101/59348101-e0c9e400-8d48-11e9-98d3-dd5c26c1826d.png)

**Comment by DataHippo93** [comment]
I want to get an azure token with permissions to read all users and group assignments in graph API and do it everyday without me having to sign in. Is this possible with your package?

**Comment by Hong-Revo** [comment]
I suspect you have a misconfigured app in AAD.

- Remove the "web" redirect, and add a "public client (mobile and desktop)" redirect to `http://localhost:1410`
- Uncheck the box next to `https://login.microsoftonline.com/common/oauth2/nativeclient`

Once you have a valid token, you should be able to reuse it any number of times. Just make sure you add the `offline_access` scope so that AzureAuth can refresh it automatically.

**Comment by DataHippo93** [comment]
Works. If I missed it, I apologize but you may want to mention how to configure your app in the documentation more explicitly.

**Comment by Hong-Revo** [comment]
Well, app creation and configuration is a big subject, and technically only somewhat related to this package. I'll see what I can do, maybe add another vignette.
