### ISSUE TITLE
Suggestion for vignettes

### ISSUE THREAD

**Issue by doncqueurs** [Azure/AzureAuth#54]
Thought it is not really the scope of the 'vignettes', but I think it would be helpful. I love the idea of using AzureAuth for a Shiny app, but I find it hard to figure out how to find my way around in the Azure Portal and get things organized there so I can ensure that only authenticated and authorized users can access the content of the Shiny App.

**Comment by hongooi73** [comment]
This is actually part the AAD quickstart guide to registering an app: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

I'll add a link to it in the scenarios vignette

**Comment by doncqueurs** [comment]
Thanks for the link. I still haven't gotten my head around how it all works in practice but I believe it may be worth to add this link as well to the vignette.
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users
