### ISSUE TITLE
Consider using random port in build_authorization_uri

### ISSUE THREAD

**Issue by smingerson** [Azure/AzureAuth#55]
Currently, the [port is hard-coded to 1410](https://github.com/Azure/AzureAuth/blob/6f6ecf4ea47e3da35afe1e05e5c5a196a00b8aae/R/flow_init.R#L56).

Rarely, at least for auth "client_credentials", authorization fails unexpectedly. Then, the httpuv server process is not terminated, even on R session restart. Attempting to authenticate again leads to an error, because httpuv cannot start the server since the port is already in use. The solutions are to either restart the machine or find and kill the process manually. Sometimes neither may be possible if running on a remote server with limited privileges. 

Unfortunately, I don't have any more information on why authorization fails. For me, it happens when I load an internal package which initializes an AzureKeyVault connection in `.onLoad()`, which might be related.

httpuv now has a `randomPort()` function which could be used, although I see httpuv is Suggests, and I'm not sure if `build_authorization_uri()` is only used in httpuv-requiring functions.

**Comment by hongooi73** [comment]
All options can be changed via the `...` argument, as shown in the examples to `?get_authorization_uri`, the Shiny vignette, and a few other places.

I've encountered a failure in httpuv to load a few times, but it hasn't affected subsequent calls. Seems to be something in the package that changed a few years back.
