### ISSUE TITLE
What's the difference between authorization_code flow with the password arg and the client_credentials flow?

### ISSUE THREAD

**Issue by mjkanji** [Azure/AzureAuth#59]
This is less of an issue and more of a question. Consider the following two examples from the docs for `get_azure_token`:

```
# authorization_code flow with app registered in AAD as a web rather than a native client:
# supply the client secret in the password arg
get_azure_token("https://management.azure.com/", "mytenant", "app_id",
                password="app_secret", auth_type="authorization_code")

# to default to the client_credentials method, supply the app secret as the password
get_azure_token("https://management.azure.com/", tenant="mytenant", app="app_id",
                password="app_secret")
```

In both cases, we supply the app_id and the app/client secret. As such, what is the difference between the `authorization_code` flow with the password defined vs. just using the `client_credentials` flow? 

Is it something like a two-stage process (i.e., you have to have the right client secret and you also have to log into AAD with the right credentials and so it's potentially more secure than just using just the `client_credentials`?

**Comment by hongooi73** [comment]
Hi, sorry for the late reply.

The `auth_type` arg controls which authorization flow is used, with the possible choices being listed [here](https://docs.microsoft.com/en-au/azure/active-directory/develop/v2-overview) (Reference -> Authentication protocols -> OAuth 2.0 and OpenID Connect protocols). When you select `auth_type="authorization_code"`, you also have the option of supplying a client secret in the `password` arg; this is required if your app ID is for a web app. In most cases where R is involved you won't be using a web app, so you don't usually need to do this.
