### ISSUE TITLE
Access token using Service Principal

### ISSUE THREAD

**Issue by Sharathmk99** [Azure/AzureAuth#7]
Hi Guys,
I'm trying to call a REST API which is protected by AzureAD authentication. From Postman REST client it works like,
https://example.com/getexample
Header: Authorization: Bearer <access_token>. This works great if i get token of the user interactively(example device_code or MFA).

As i wanted to run R code Non Interactively, i'm trying to authenticate the REST endpoint by service principal. I have created Service Principal(Native app) and secret for the same. I was able to get access_token from this package as well as below curl command
curl -X POST -d 'grant_type=client_credentials&client_id=[client id]&client_secret=[client secret]&resource=[client id of the server]' https://login.microsoftonline.com/[tenant]/oauth2/token

But if i pass this generated token to REST endpoint i get 401.

The REST server is built in nodejs with azure-passport node package. 

Please help how to authenticate a custom REST endpoint with service principal and secret.

Regards,
Sharath

**Comment by Hong-Revo** [comment]
This doesn't seem to have anything to do with R. If you're having trouble with AAD in general, try contacting tech support or asking a question on StackOverflow. That said, check that you've assigned your service principal the correct role for your API.
