### ISSUE TITLE
get a token without app_id?

### ISSUE THREAD

**Issue by idavydov** [Azure/AzureAuth#78]
With azure cli it is possible to use the following commands to get a token without providing an app_id:

```
az account get-access-token --scope https://cognitiveservices.azure.com/.default
```

When I try to call:

```
AzureAuth::get_azure_token(
  "https://cognitiveservices.azure.com/.default",
  "organizations"
)
```

I get:

```
Error in AzureAuth::get_azure_token("https://cognitiveservices.azure.com/.default",  : 
  argument "app" is missing, with no default
```

Is it at all possible to perform this using AzureAuth?

**Comment by hongooi73** [comment]
You need to supply an app ID.

Think of AzureAuth as being like an SDK for working with Azure Active Directory. It works with an app (R script) that you create; it isn't an app in itself.
