### ISSUE TITLE
Microsoft Authentication Library

### ISSUE THREAD

**Issue by doncqueurs** [Azure/AzureAuth#82]
On the portal.azure.com I encountered the following message: 

"Starting June 30th, 2020 we will no longer add any new features to Azure Active Directory Authentication Library (ADAL) and Azure Active Directory Graph. We will continue to provide technical support and security updates but we will no longer provide feature updates. Applications will need to be upgraded to Microsoft Authentication Library (MSAL) and Microsoft Graph." 

I am curious to learn whether the AzureAuth package will get any updates that will facilitate this new authentication approach?

**Comment by hongooi73** [comment]
This is just deprecating Microsoft's official libraries for authentication. The underlying APIs that these libraries use haven't changed. AzureAuth doesn't use the official libraries, it talks directly to the APIs using other R packages (httr, curl, etc). Thus the message doesn't apply here.
